hello/hello/urls.py
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include
from django.conf import settings

from webapp.views import GalleryMore, GalleryAdd, GalleryChange, DeleteGallery, IndexViewGallery, ChoiceGallery, UnChoiceForGallery
from webapp.views import IndexViewAlbom, AlbomMore, AlbomChange, AlbomDelete, AlbomAdd, ChoiceForAlbom, UnChoiceForAlbom
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexViewAlbom.as_view(), name='main_page'),
    # path('more/<int:pk>/', Good_more.as_view(), name='see_good'),
    path('more/<int:pk>/', AlbomMore.as_view(), name='see_albom'),
    path('fotos/<int:pk>/', IndexViewGallery.as_view(), name='see_fotos'),
    path('add/', AlbomAdd.as_view(), name='add_albom'),
    path('edit/<int:pk>/', AlbomChange.as_view(), name='change_albom'),
    path('delete/<int:pk>/', AlbomDelete.as_view(), name='del_albom'),
    path('<int:pk>/add_foto/', GalleryAdd.as_view(), name='adding_foto'),
    path('delete_foto/<int:pk>/', DeleteGallery.as_view(), name='delete_foto'),
    path('update/<int:pk>/', GalleryChange.as_view(), name='update_foto'),
    path('more_foto/<int:pk>/', AlbomMore.as_view(), name='see_foto'),
    path('<int:pk>/choice_gallery', ChoiceGallery.as_view(), name='choice_gallery'),
    path('<int:pk>/unchoice_gallery', UnChoiceForGallery.as_view(), name='unchoice_gallery'),
    path('<int:pk>/choice_albom', ChoiceForAlbom.as_view(), name='choice_albom'),
    path('<int:pk>/unchoice_albom', UnChoiceForAlbom.as_view(), name='unchoice_albom'),
    path('accounts/', include('accounts.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

hello/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models


status_choice = [('public', 'публичная'), ('private', 'приватная')]


class Albom(models.Model):
    name = models.CharField(max_length=150, null=False, blank=False, verbose_name='название')
    description = models.TextField(null=True, blank=True, verbose_name='Описание')
    user = models.ForeignKey(get_user_model(),  on_delete=models.SET_NULL, null=True, related_name='alboms')
    created_at = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=50, null=False, choices=status_choice, blank=False, default='публичная')

    class Meta:
        db_table = 'alboms'
        verbose_name = 'albom'
        verbose_name_plural = 'alboms'

    def str(self):
        return f'{self.name}: {self.description}'



class Gallery(models.Model):
    image = models.ImageField(upload_to='images', null=False, blank=False)
    caption = models.CharField(max_length=200, null=False, blank=False, verbose_name='подпись для картинки')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата загрузки')
    user = models.ForeignKey(get_user_model(), null=False, blank=False, related_name='gallery', verbose_name='автор',
                             on_delete=models.CASCADE)

    albom = models.ForeignKey('webapp.Gallery', on_delete=models.CASCADE, related_name='gallery', verbose_name='albom',
                             null=True, blank=True)
    status = models.CharField(max_length=50, null=False, choices=status_choice, blank=False, default='публичная')
    class Meta:
        db_table = 'gallery'
        verbose_name = 'image'
        verbose_name_plural = 'images'

    def __str__(self):
        return f'{self.id}. {self.caption}'


class ChoiceAlbom(models.Model):
    albom = models.ForeignKey(
        'webapp.Albom',
        on_delete=models.CASCADE,
        related_name='choice_albom',
        verbose_name='Альбом',
        null=False,
        blank=False)

    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.SET_NULL,
        null=True,
        related_name='user_choice_albom'
    )

    class Meta:
        db_table = 'choice_albom'
        verbose_name = 'choice'
        verbose_name_plural = 'choices'

    def __str__(self):
        return f'{self.albom}: {self.user}'

class ChoiceGallery(models.Model):
        gallery = models.ForeignKey(
            'webapp.Gallery',
            on_delete=models.CASCADE,
            related_name='choice_gallery',
            verbose_name='фото',
            null=False,
            blank=False)

        user = models.ForeignKey(
            get_user_model(),
            on_delete=models.SET_NULL,
            null=True,
            related_name='user_choice_gallery'
        )

        class Meta:
            db_table = 'choice_gallery'
            verbose_name = 'choice'
            verbose_name_plural = 'choices'

        def __str__(self):
            return f'{self.gallery}: {self.user}'

hello/webapp/forms.py
from django import forms
from webapp.models import Gallery, Albom


class Galleryform(forms.ModelForm):
    class Meta:
        model=Gallery
        fields=('image', 'caption', 'user', 'status')


class GalleryDeleteForm(forms.Form):
    caption=forms.CharField(max_length=100, required=True, label='Введите текст подписи  чтобы удалить его')



class SimpleSearchForm(forms.Form):

    search = forms.CharField(max_length=100, required=False, label="Найти")


class AlbomForms(forms.ModelForm):

    class Meta:
        model=Albom
        fields = ['name', 'description', 'created_at', 'status']


# class PrivateForm(forms.ModelForm):
#
#     class Meta:
#         model=Albom
#         fields = ['text_review', 'rating', 'moderation']

hello/webapp/views/albom.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden, HttpResponse
from django.utils.http import urlencode
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.base import View

from webapp.forms import AlbomForms, SimpleSearchForm
from webapp.models import Albom, Gallery
from django.urls import reverse_lazy
from django.db.models import Q

from webapp.views.gallery import ChoiceForGallery


class IndexViewAlbom(ListView):
    model = Albom
    template_name = 'Albom/index.html'
    context_object_name = 'alboms'
    paginate_by = 3
    paginate_orphans = 1


    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *args, object_list = None, **kwargs):
        context = super().get_context_data(object_list= object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})

        choices_alboms = []
        gallery_choice = []
        if self.request.user.is_authenticated:
            choices = ChoiceForAlbom.objects.filter(user=self.request.user)
            choices_gallery = ChoiceForGallery.objects.filter(user = self.request.user)
            for choice in choices:
                choices_alboms.append(choice.albom.pk)
            for choice_gallery in choices_gallery:
                gallery_choice.append(choice_gallery.gallery.pk)

        context['choices_alboms'] = choices_alboms
        context['choices_gallery'] = gallery_choice
        return context
    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(name__icontains=self.search_value)  | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset.order_by('name')

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None




class AlbomMore(DetailView):
    model = Albom
    template_name = 'Albom/albom_more.html'

    def get_context_data(self, **kwargs):
        user = self.request.user
        if user.is_authenticated and user.groups.filter(name='moderator').exists():
            kwargs['galleries'] = Gallery.objects.filter(gallery__pk=self.get_object().pk)

        return super().get_context_data(**kwargs)



class AlbomAdd(LoginRequiredMixin, CreateView):
    template_name = 'Albom/add_albom.html'
    model = Albom
    form_class = AlbomForms

    def get_success_url(self):
        return reverse('see_albom', kwargs = {'pk': self.object.pk})


class AlbomChange(LoginRequiredMixin, UpdateView):
    model = Albom
    template_name = 'Albom/update_albom.html'
    form_class = AlbomForms
    context_object_name = 'alboms'

    def get_success_url(self):
        return reverse('see_albom', kwargs={'pk': self.object.pk})




class AlbomDelete(LoginRequiredMixin, DeleteView):
    template_name = 'Albom/albom_delete.html'
    model = Albom
    context_object_name = 'alboms'
    success_url = reverse_lazy('main_page')



class ChoiceForAlbom(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        albom = get_object_or_404(Albom, pk=self.kwargs.get('pk'))
        user = request.user
        try:
            ChoiceForAlbom.objects.get(albom=albom, user=user)
            return HttpResponseForbidden("error")
        except ChoiceForAlbom.DoesNotExist:
            ChoiceForAlbom.objects.create(albom=albom, user=user)
        return HttpResponse(albom.choice_albom)




class UnChoiceForAlbom(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        albom = get_object_or_404(Albom, pk=self.kwargs.get('pk'))
        user = request.user
        try:
            choice = ChoiceForAlbom.objects.get(albom=albom, user=user)
            choice.delete()
            return HttpResponse(albom.choice_albom)
        except ChoiceForAlbom.DoesNotExist:
            return HttpResponseForbidden("error")

hello/webapp/views/gallery.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseForbidden, HttpResponse
from django.utils.http import urlencode
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from webapp.forms import Galleryform, GalleryDeleteForm, SimpleSearchForm
from webapp.models import Gallery, Albom, ChoiceGallery
from django.urls import reverse_lazy
from django.db.models import Q


class IndexViewGallery(ListView):
    template_name = 'Galery/index.html'
    model = Gallery
    context_object_name = 'galleries'



class GalleryMore(DetailView):
    model = Gallery
    template_name = 'Galery/gallery_detail.html'

    def get_context_data(self, **kwargs):
        user = self.request.user
        # if user.is_authenticated and user.groups.filter(name='moderator').exists():
        #     kwargs['reviews'] = Review.objects.filter(good__pk=self.get_object().pk)
        # else:
        #     kwargs['reviews'] = Review.objects.filter(moderation=True, good__pk=self.get_object().pk)
        return super().get_context_data(**kwargs)



class GalleryAdd(LoginRequiredMixin, CreateView):
    template_name = 'Galery/galery_add.html'
    model = Gallery
    form_class = Galleryform

    # def get_success_url(self):
    #     return reverse(Gallery, kwargs = {'pk': self.object.pk})

    def form_valid(self, form):
        albom = get_object_or_404(Albom, pk=self.kwargs.get('pk'))
        gallery = form.save(commit=False)
        gallery.albom = albom
        gallery.user = self.request.user
        gallery.save()
        return redirect('see_albom', pk=albom.pk)

class GalleryChange(PermissionRequiredMixin, UpdateView):
    model = Gallery
    template_name = 'Galery/change_galery.html'
    form_class = Galleryform
    context_object_name = 'galleries'
    permission_required = 'webapp.change_gallery'

    def has_permission(self, request):
        return super().has_permission() or self.request.user == self.get_object().user



    def get_success_url(self):
        return reverse('see_gallery', kwargs={'pk': self.object.pk})



class DeleteGallery(PermissionRequiredMixin, DeleteView):
    model = Gallery
    permission_required = 'webapp.delete_gallery'
    template_name = 'Galery/galery_del.html'

    def has_permission(self):
        return super().has_permission() or self.request.user == self.get_object().user

    def get_success_url(self):
        return reverse('see_albom', kwargs={'pk': self.object.albom.pk})



class ChoiceForGallery(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        gallery = get_object_or_404(Gallery, pk=self.kwargs.get('pk'))
        user = request.user
        try:
            ChoiceGallery.objects.get(gallery=gallery, user=user)
            return HttpResponseForbidden("error")
        except ChoiceGallery.DoesNotExist:
            ChoiceGallery.objects.create(gallery=gallery, user=user)
        return HttpResponse(gallery.choice_gallery)


class UnChoiceForGallery(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        gallery = get_object_or_404(Gallery, pk=self.kwargs.get('pk'))
        user = request.user
        try:
            choice_gallery = ChoiceGallery.objects.get(gallery=gallery, user=user)
            choice_gallery.delete()
            return HttpResponse(gallery.choice_gallery)
        except ChoiceGallery.DoesNotExist:
            return HttpResponseForbidden("error")

hello/webapp/templates/Albom/add_albom.html
{% extends 'partial/../base.html' %}
{% block content %}
    <a href="{% url "main_page" %}">На список альбомов</a>

    <form action="" method="post">
        {% include "partial/base_form.html" with button_text="Create"%}
    </form>


{% endblock content %}

hello/webapp/templates/Albom/albom_delete.html
{% extends "partial/../base.html" %}
{% block title %} Удалить альбом{% endblock %}
{% block menu %}
    <li><a href="{% url 'main_page'%}">Назад</a></li>
{% endblock %}
{% block content %}
    <h1>Точно хотите удалить? </h1>
    <form method="POST" action="{% url "del_albom" alboms.pk %}" class="text-center">
        {% csrf_token %}
        <p><input type="submit" value="Подтвердить!"></p>
        <p><a href="{% url "see_albom" alboms.pk%}">Cancel</a></p>
    </form>
{% endblock %}

hello/webapp/templates/Albom/albom_more.html
{% extends "base.html" %}
{% load static %}
{% block menu %}
{#    {% if perms.webapp.add_goods %}#}
{#    <li><a href="{% url "add_good" %}">Добавить товар</a></li>#}
{#    {% endif %}#}
{#{% if perms.webapp.change_goods %}#}
{#    <li><a href="{% url "change_good" goods.pk%}">Изменить товар</a></li>#}
{#    {% endif %}#}
{#{% if perms.webapp.delete_goods %}#}
{#    <li><a href="{% url "del_good" goods.pk %}">Удалить товар</a></li>#}
{#    {% endif %}#}
{% endblock menu %}
{% block page_header %}Альбом {{ albom.id }}{% endblock page_header %}
{% block content %}
     <div>
    Название: {{ albom.name }}
    </div>
    <div>
    статус: {{ albom.status }}
    </div>
    <div>
    Описание: {{ albom.description }}
    </div>


{% if user.is_authenticated %}
    <div class="col px-md-5"><div class="p-3 border bg-light"><a href="{% url "adding_foto" albom.pk %}"> добавить фото</a></div></div>
{% endif %}
{% if user.is_authenticated %}
    <div class="col px-md-5"><div class="p-3 border bg-light"><a href="{% url "see_fotos" albom.pk %}"> Все фото альбома</a></div></div>
{% endif %}
          {% if comment.pk not in likes_comments %}
    <a data-comment_counter="comment_counter{{ comment.pk }}" onclick="likeComment(event)" href="{% url 'article:like_comment' comment.pk %}"><i class="bi bi-heart"></i></a>
    {% else %}
    <a data-comment_counter="comment_counter{{ comment.pk }}" onclick="unlikeComment(event)"  href="{% url 'article:unlike_comment' comment.pk %}"><i class="bi bi-heart-fill"></i></a>
    {% endif %}
    <p id="comment_counter{{ comment.pk }}">{{ comment.like_comment.count }}</p>
        <div>


{% endblock content %}

hello/webapp/templates/Albom/index.html
{% extends 'base.html' %}

{#{% block menu %}<li><a href="{% url "add_good" %}">Добавить товар</a></li>{% endblock menu %}#}
{% block title %}Все альбомы{% endblock title %}
{% block page_header %}альбомы{% endblock page_header %}
{% block content %}
    <div >


        {% if not alboms %}
            <h1>Нет Альбомов</h1>
        {% else %}

            {% include 'Galery/../partial/simple_search.html' %}


            {% if is_paginated %}

                 {% include 'Galery/pagination.html' %}
                {% endif %}

         {% for albom in alboms %}

        <div>id: {{ albom.id }} </div>
<div>

    </div>
        <div>name: <a href="{% url "see_albom" albom.id %}">{{albom.name }}</a> </div>
        <div>data: {{ albom.created_at }} </div>
        <div>author: {{ albom.user }} </div>
        <div>description: {{ albom.description }} </div>
                 {% if albom.pk not in choices_alboms %}
    <a id="albom_choice{{ albom.pk }}" onclick="choiceAlbom(event)" href="{% url 'choice_albom' albom.pk %}"><i class="bi bi-bookmark"></i></a>
    {% else %}
    <a id="albom_unchoice{{ albom.pk }}" onclick="unchoiceAlbom(event)"  href="{% url 'unchoice_albom' albom.pk %}"><i class="bi bi-bookmark-fill"></i></a>
    {% endif %}

{% endfor %}


    {% endif %}
     {% if user.is_authenticated and perms.webapp.change_albom %}
     <a href="{% url 'change_albom' alboms.pk %}">update</a>

{% endif %}

                {% if user.is_authenticated and perms.webapp.delete_albom %}

                     <a href="{% url 'del_albom' alboms.pk %}">remove</a>
                {% endif %}


    </div>

{% endblock content %}

hello/webapp/templates/Albom/update_albom.html
{% extends 'partial/../base.html' %}

{% block content %}


    <form action="" method="post">
        {% include 'partial/base_form.html' with button_text="изменить"%}
    </form>


{% endblock content %}