hello/hello/urls.py
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include
from django.conf import settings

from webapp.views import GalleryMore, GalleryAdd, GalleryChange, DeleteGallery, IndexViewGallery, ChoiceGallery, UnChoiceForGallery
from webapp.views import IndexViewAlbom, AlbomMore, AlbomChange, AlbomDelete, AlbomAdd, ChoiceForAlbom, UnChoiceForAlbom
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexViewAlbom.as_view(), name='main_page'),
    # path('more/<int:pk>/', Good_more.as_view(), name='see_good'),
    path('more/<int:pk>/', AlbomMore.as_view(), name='see_albom'),
    path('fotos/<int:pk>/', IndexViewGallery.as_view(), name='see_fotos'),
    path('add/', AlbomAdd.as_view(), name='add_albom'),
    path('edit/<int:pk>/', AlbomChange.as_view(), name='change_albom'),
    path('delete/<int:pk>/', AlbomDelete.as_view(), name='del_albom'),
    path('<int:pk>/add_foto/', GalleryAdd.as_view(), name='adding_foto'),
    path('delete_foto/<int:pk>/', DeleteGallery.as_view(), name='delete_foto'),
    path('update/<int:pk>/', GalleryChange.as_view(), name='update_foto'),
    path('more_foto/<int:pk>/', AlbomMore.as_view(), name='see_foto'),
    path('<int:pk>/choice_gallery', ChoiceGallery.as_view(), name='choice_gallery'),
    path('<int:pk>/unchoice_gallery', UnChoiceForGallery.as_view(), name='unchoice_gallery'),
    path('<int:pk>/choice_albom', ChoiceForAlbom.as_view(), name='choice_albom'),
    path('<int:pk>/unchoice_albom', UnChoiceForAlbom.as_view(), name='unchoice_albom'),
    path('accounts/', include('accounts.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

hello/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models


status_choice = [('public', 'публичная'), ('private', 'приватная')]


class Albom(models.Model):
    name = models.CharField(max_length=150, null=False, blank=False, verbose_name='название')
    description = models.TextField(null=True, blank=True, verbose_name='Описание')
    user = models.ForeignKey(get_user_model(),  on_delete=models.SET_NULL, null=True, related_name='alboms')
    created_at = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=50, null=False, choices=status_choice, blank=False, default='публичная')

    class Meta:
        db_table = 'alboms'
        verbose_name = 'albom'
        verbose_name_plural = 'alboms'

    def str(self):
        return f'{self.name}: {self.description}'



class Gallery(models.Model):
    image = models.ImageField(upload_to='images', null=False, blank=False)
    caption = models.CharField(max_length=200, null=False, blank=False, verbose_name='подпись для картинки')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата загрузки')
    user = models.ForeignKey(get_user_model(), null=False, blank=False, related_name='gallery', verbose_name='автор',
                             on_delete=models.CASCADE)

    albom = models.ForeignKey('webapp.Gallery', on_delete=models.CASCADE, related_name='gallery', verbose_name='albom',
                             null=True, blank=True)
    status = models.CharField(max_length=50, null=False, choices=status_choice, blank=False, default='публичная')
    class Meta:
        db_table = 'gallery'
        verbose_name = 'image'
        verbose_name_plural = 'images'

    def __str__(self):
        return f'{self.id}. {self.caption}'


class ChoiceAlbom(models.Model):
    albom = models.ForeignKey(
        'webapp.Albom',
        on_delete=models.CASCADE,
        related_name='choice_albom',
        verbose_name='Альбом',
        null=False,
        blank=False)

    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.SET_NULL,
        null=True,
        related_name='user_choice_albom'
    )

    class Meta:
        db_table = 'choice_albom'
        verbose_name = 'choice'
        verbose_name_plural = 'choices'

    def __str__(self):
        return f'{self.albom}: {self.user}'

class ChoiceGallery(models.Model):
        gallery = models.ForeignKey(
            'webapp.Gallery',
            on_delete=models.CASCADE,
            related_name='choice_gallery',
            verbose_name='фото',
            null=False,
            blank=False)

        user = models.ForeignKey(
            get_user_model(),
            on_delete=models.SET_NULL,
            null=True,
            related_name='user_choice_gallery'
        )

        class Meta:
            db_table = 'choice_gallery'
            verbose_name = 'choice'
            verbose_name_plural = 'choices'

        def __str__(self):
            return f'{self.gallery}: {self.user}'

hello/webapp/forms.py
from django import forms
from webapp.models import Gallery, Albom


class Galleryform(forms.ModelForm):
    class Meta:
        model=Gallery
        fields=('image', 'caption', 'user', 'status')


class GalleryDeleteForm(forms.Form):
    caption=forms.CharField(max_length=100, required=True, label='Введите текст подписи  чтобы удалить его')



class SimpleSearchForm(forms.Form):

    search = forms.CharField(max_length=100, required=False, label="Найти")


class AlbomForms(forms.ModelForm):

    class Meta:
        model=Albom
        fields = ['name', 'description', 'created_at', 'status']


# class PrivateForm(forms.ModelForm):
#
#     class Meta:
#         model=Albom
#         fields = ['text_review', 'rating', 'moderation']

hello/webapp/views/albom.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden, HttpResponse
from django.utils.http import urlencode
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.base import View

from webapp.forms import AlbomForms, SimpleSearchForm
from webapp.models import Albom, Gallery
from django.urls import reverse_lazy
from django.db.models import Q

from webapp.views.gallery import ChoiceForGallery


class IndexViewAlbom(ListView):
    model = Albom
    template_name = 'Albom/index.html'
    context_object_name = 'alboms'
    paginate_by = 3
    paginate_orphans = 1


    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *args, object_list = None, **kwargs):
        context = super().get_context_data(object_list= object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})

        choices_alboms = []
        gallery_choice = []
        if self.request.user.is_authenticated:
            choices = ChoiceForAlbom.objects.filter(user=self.request.user)
            choices_gallery = ChoiceForGallery.objects.filter(user = self.request.user)
            for choice in choices:
                choices_alboms.append(choice.albom.pk)
            for choice_gallery in choices_gallery:
                gallery_choice.append(choice_gallery.gallery.pk)

        context['choices_alboms'] = choices_alboms
        context['choices_gallery'] = gallery_choice
        return context
    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(name__icontains=self.search_value)  | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset.order_by('name')

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None




class AlbomMore(DetailView):
    model = Albom
    template_name = 'Albom/albom_more.html'

    def get_context_data(self, **kwargs):
        user = self.request.user
        if user.is_authenticated and user.groups.filter(name='moderator').exists():
            kwargs['galleries'] = Gallery.objects.filter(gallery__pk=self.get_object().pk)

        return super().get_context_data(**kwargs)



class AlbomAdd(LoginRequiredMixin, CreateView):
    template_name = 'Albom/add_albom.html'
    model = Albom
    form_class = AlbomForms

    def get_success_url(self):
        return reverse('see_albom', kwargs = {'pk': self.object.pk})


class AlbomChange(LoginRequiredMixin, UpdateView):
    model = Albom
    template_name = 'Albom/update_albom.html'
    form_class = AlbomForms
    context_object_name = 'alboms'

    def get_success_url(self):
        return reverse('see_albom', kwargs={'pk': self.object.pk})




class AlbomDelete(LoginRequiredMixin, DeleteView):
    template_name = 'Albom/albom_delete.html'
    model = Albom
    context_object_name = 'alboms'
    success_url = reverse_lazy('main_page')



class ChoiceForAlbom(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        albom = get_object_or_404(Albom, pk=self.kwargs.get('pk'))
        user = request.user
        try:
            ChoiceForAlbom.objects.get(albom=albom, user=user)
            return HttpResponseForbidden("error")
        except ChoiceForAlbom.DoesNotExist:
            ChoiceForAlbom.objects.create(albom=albom, user=user)
        return HttpResponse(albom.choice_albom)




class UnChoiceForAlbom(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        albom = get_object_or_404(Albom, pk=self.kwargs.get('pk'))
        user = request.user
        try:
            choice = ChoiceForAlbom.objects.get(albom=albom, user=user)
            choice.delete()
            return HttpResponse(albom.choice_albom)
        except ChoiceForAlbom.DoesNotExist:
            return HttpResponseForbidden("error")

hello/webapp/views/gallery.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseForbidden, HttpResponse
from django.utils.http import urlencode
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from webapp.forms import Galleryform, GalleryDeleteForm, SimpleSearchForm
from webapp.models import Gallery, Albom, ChoiceGallery
from django.urls import reverse_lazy
from django.db.models import Q


class IndexViewGallery(ListView):
    template_name = 'Galery/index.html'
    model = Gallery
    context_object_name = 'galleries'



class GalleryMore(DetailView):
    model = Gallery
    template_name = 'Galery/gallery_detail.html'

    def get_context_data(self, **kwargs):
        user = self.request.user
        # if user.is_authenticated and user.groups.filter(name='moderator').exists():
        #     kwargs['reviews'] = Review.objects.filter(good__pk=self.get_object().pk)
        # else:
        #     kwargs['reviews'] = Review.objects.filter(moderation=True, good__pk=self.get_object().pk)
        return super().get_context_data(**kwargs)



class GalleryAdd(LoginRequiredMixin, CreateView):
    template_name = 'Galery/galery_add.html'
    model = Gallery
    form_class = Galleryform

    # def get_success_url(self):
    #     return reverse(Gallery, kwargs = {'pk': self.object.pk})

    def form_valid(self, form):
        albom = get_object_or_404(Albom, pk=self.kwargs.get('pk'))
        gallery = form.save(commit=False)
        gallery.albom = albom
        gallery.user = self.request.user
        gallery.save()
        return redirect('see_albom', pk=albom.pk)

class GalleryChange(PermissionRequiredMixin, UpdateView):
    model = Gallery
    template_name = 'Galery/change_galery.html'
    form_class = Galleryform
    context_object_name = 'galleries'
    permission_required = 'webapp.change_gallery'

    def has_permission(self, request):
        return super().has_permission() or self.request.user == self.get_object().user



    def get_success_url(self):
        return reverse('see_gallery', kwargs={'pk': self.object.pk})



class DeleteGallery(PermissionRequiredMixin, DeleteView):
    model = Gallery
    permission_required = 'webapp.delete_gallery'
    template_name = 'Galery/galery_del.html'

    def has_permission(self):
        return super().has_permission() or self.request.user == self.get_object().user

    def get_success_url(self):
        return reverse('see_albom', kwargs={'pk': self.object.albom.pk})



class ChoiceForGallery(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        gallery = get_object_or_404(Gallery, pk=self.kwargs.get('pk'))
        user = request.user
        try:
            ChoiceGallery.objects.get(gallery=gallery, user=user)
            return HttpResponseForbidden("error")
        except ChoiceGallery.DoesNotExist:
            ChoiceGallery.objects.create(gallery=gallery, user=user)
        return HttpResponse(gallery.choice_gallery)


class UnChoiceForGallery(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        gallery = get_object_or_404(Gallery, pk=self.kwargs.get('pk'))
        user = request.user
        try:
            choice_gallery = ChoiceGallery.objects.get(gallery=gallery, user=user)
            choice_gallery.delete()
            return HttpResponse(gallery.choice_gallery)
        except ChoiceGallery.DoesNotExist:
            return HttpResponseForbidden("error")

hello/webapp/templates/Galery/change_galery.html
{% extends 'base.html' %}

{% block menu %}<li><a href="{% url "see_albom" galleries.id %}">На товар</a></li>{% endblock menu %}
{% block page_header %}'Изменить фото {{ albom.id }}{% endblock page_header %}

{% block content %}
    <form action="{% url "update_foto" galleries.id %}" method="post">
        {% include "partial/base_form.html" with button_text="Изменить фото" %}
    </form>
{% endblock content %}

hello/webapp/templates/Galery/galery_add.html
{% extends 'partial/../base.html' %}
{% block content %}
    <a href="{% url "main_page" %}">На список альбомов</a>

    <form action="" method="post">
        {% include "partial/base_form.html" with button_text="Create"%}
    </form>


{% endblock content %}

hello/webapp/templates/Galery/galery_del.html
{% extends 'base.html' %}

{% block title %}Подтвердите удаление товара{% endblock %}
{% block page_header %}Вы уверены, что хотите удалить этот товар {{ good.name }}?{% endblock page_header %}

{% block content%}
    <form action="{% url "delete_foto" galleries.id %}", method="POST">
        {% include 'partial/base_form.html' with button_text="Да, я хочу удалить фото" %}
        <a href="{% url "see_albom" galleries.id %}">Отмена. Код красный. КОД КРАСНЫЙ!!</a>
    </form>
{% endblock content %}

hello/webapp/templates/Galery/gallery_detail.html
{% extends "base.html" %}
{% load static %}
{% block menu %}
    {% if perms.webapp.add_gallery %}
    <li><a href="{% url "adding_foto" %}">Добавить фото</a></li>
    {% endif %}
{% if perms.webapp.add_gallery%}
    <li><a href="{% url "update_foto" gallery.pk%}">Изменить фото</a></li>
    {% endif %}
{% if perms.webapp.delete_gallery %}
    <li><a href="{% url "delete_foto" gallery.pk %}">Удалить фото</a></li>
    {% endif %}
{% endblock menu %}
{% block page_header %}Фото {{ gallery.id }}{% endblock page_header %}
{% block content %}

    <div>
        {% if gallery.image %}
        <img src="{{ gallery.image.url }}" alt="">

{% endif %}
    </div>
         <div>
    Автор: {{ gallery.user }}
    </div>
    <div>
    Подпись: {{ gallery.caption }}
    </div>
    <div>
    Дата: {{ gallery.created_at }}
    </div>
{##}
{#{% if user.is_authenticated %}#}
{#    <div class="col px-md-5"><div class="p-3 border bg-light"><a href="{% url "adding_review" gallery.pk %}"> добавить в альбом</a></div></div>#}
{#{% endif %}#}
{# {% include 'Review/index.html' %}#}
{#    <h3>Rating: {{ goods.avr_rating.rating|default:0 }}</h3>#}
{% endblock content %}

hello/webapp/templates/Galery/index.html
{% extends 'base.html' %}


{% block content %}


    {% if not galleries %}
        <h2>Нету фотографий</h2>

    {% else %}


         {% for gallery in galleries %}

        <div>id: {{ gallery.id }} </div>
<div>
        {% if gallery.image %}
        <img src="{{ gallery.image.url }}" alt="">

{% endif %}
    </div>
        <div>caption: <a href="{% url "see_foto" gallery.id %}">{{ gallery.caption }}</a> </div>
        <div>data: {{ gallery.created_at }} </div>
        <div>author: {{ gallery.user }} </div>


             {% if perms.webapp.add_gallery %}
    <li><a href="{% url "adding_foto" %}">Добавить фото</a></li>
    {% endif %}
{% if perms.webapp.change_gallery %}
    <li><a href="{% url "update_foto" gallery.pk%}">Изменить фото</a></li>
    {% endif %}
{% if perms.webapp.delete_gallery %}
    <li><a href="{% url "delete_foto" gallery.pk %}">Удалить фото</a></li>
    {% endif %}
{% endfor %}


    {% endif %}


{% endblock %}

hello/webapp/templates/Galery/pagination.html
<div class="pagination">

    <span class="step-links">

        <a href="?{% if query %}{{ query }}&{% endif %}page=1">&laquo; В начало</a>

        {% if page_obj.has_previous %}

            <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}">Назад</a>

        {% else %}

            <span class="page-disabled">Назад</span>

        {% endif %}


        <form class="current-page" method="get">

               <label for="page">
                   {% if search %}<input type="hidden" name="search" value="{{ search }}">{% endif %}
                   Страница <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                   из {{ page_obj.paginator.num_pages }}.

               </label>
        </form>



        {% if page_obj.has_next %}

            <a href="?page={{ page_obj.next_page_number }}">Далее</a>

        {% else %}

            <span class="page-disabled">Далее</span>

        {% endif %}

        <a href="?page={{ page_obj.paginator.num_pages }}">В конец &raquo;</a>

    </span>

</div>